
%{
#include "y.tab.h"     // include token definitions generated by YACC
%}

%%

// Match integer numbers
[0-9]+        { yylval = atoi(yytext); return NUMBER; }

// Operators
\+            { return PLUS; }
\-            { return MINUS; }
\*            { return MUL; }
\/            { return DIV; }

// Parentheses
\(            { return LP; }
\)            { return RP; }

// Ignore whitespace
[ \t\n]       ;

// Catch invalid characters
.             { return yytext[0]; }

%%

int yywrap() { return 1; }



//=========================================================================================


%{
#include <stdio.h>
#include <stdlib.h>

int yylex();
int yyerror(char *s);
%}

// Declare tokens coming from Lex
%token NUMBER
%token PLUS MINUS MUL DIV
%token LP RP

// Operator precedence (higher lines = lower precedence)
%left PLUS MINUS
%left MUL DIV

%%

// Start symbol
S : E { printf("Result = %d\n", $1); }
  ;

E : E PLUS E    { $$ = $1 + $3; }
  | E MINUS E   { $$ = $1 - $3; }
  | E MUL E     { $$ = $1 * $3; }
  | E DIV E     { $$ = $1 / $3; }
  | LP E RP     { $$ = $2; }
  | NUMBER      { $$ = $1; }
  ;

%%

int main() {
    printf("Enter expression: ");
    yyparse();
    return 0;
}

int yyerror(char *s) {
    printf("Invalid expression\n");
    return 0;
}





//=========================================================================================


Input:

2+3*4


Output:

Result = 14


Input:



//=========================================================================================






//=========================================================================================